# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 04:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gituserinfo',
            old_name='name',
            new_name='login',
        ),
        migrations.RemoveField(
            model_name='gituserinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Avathar URL'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='events_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Events Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='followers_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Followers Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='following_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Following Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='gists_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Gists Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='git_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Git URL'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='gravatar_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Gravatar ID'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='html_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='HTML URL'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='node_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Node ID'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='organizations_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Org. Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='received_events_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Received Events Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='repos_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Repos Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='starred_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Starred Url'),
        ),
        migrations.AddField(
            model_name='gituserinfo',
            name='subscriptions_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Subscription Url'),
        ),
    ]
