# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180701_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gituserinfo',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Avathar URL'),
        ),
        migrations.AlterField(
            model_name='gituserinfo',
            name='gravatar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Gravatar ID'),
        ),
        migrations.AlterField(
            model_name='gituserinfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gituserinfo',
            name='node_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Node ID'),
        ),
    ]
