# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180701_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_call', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='gituserinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
